repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        description: "Run 'ruff' for extremely fast Python linting"
        entry: uv run --locked ruff check
        language: system
        types: [python]
        require_serial: true
        args:
          - --force-exclude
          - --fix
          - --exit-non-zero-on-fix

      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: uv run --locked ruff format
        language: system
        types: [python]
        require_serial: true
        args:
          - --force-exclude

      - id: mypy
        name: mypy
        description: "Run mypy to check python types coherence."
        entry: uv run mypy src
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
